//Custom JS with yadcf for videos_datatable
$(document).ready(function(){
	var videos_datatable = $("#videos_datatable").DataTable();
	
	yadcf.init(videos_datatable, [{
			column_number: 6,
			data: [	{value: "201", label: "'10s"}, 
					{value: "200", label: "'00s"},
					{value: "199", label: "'90s"},
					{value: "198", label: "'80s"},
					{value: "197", label: "'70s"},
					{value: "196", label: "'60s"},
					{value: "195", label: "'50s"}
				],
			filter_container_id: "year-filter",
			filter_default_label: "Filter By Decade",
			filter_reset_button_text: "Reset"
		},{	column_number: 7,
			data: [
					"Acoustic Pop",
					"Adult Contemporary",
					"Alternative Rock",
					"Art Pop",
					"Ballad",
					"Blues Rock",
					"Contemporary folk",
					"Country",
					"Country Pop",
					"Dance",
					"Dance Pop",
					"Disco",
					"Doo-Wop",
					"EDM",
					"Electro Pop",
					"Folk Pop",
					"Folk Rock",
					"Funk",
					"Garage Rock",
					"Glam Rock",
					"Gospel",
					"Hard Rock",
					"Heavy Metal",
					"Hip Hop",
					"House",
					"Indie Pop",
					"Indie Rock",
					"Jazz",
					"Latin Pop",
					"Latin Rock",
					"Modern Rock",
					"New Wave",
					"OPM",
					"Pop",
					"Pop Ambient",
					"Pop Rock",
					"Pop Standard",
					"Post-Grunge Rock",
					"Power Pop",
					"Psychedelic",
					"Psychedelic Rock",
					"R 'n B",
					"Reggae",
					"Rhythm and Blues",
					"Rock",
					"Rock 'n Roll",
					"Soft Rock",
					"Soul",
					"Synth Pop",
					"Traditional",
					"Traditional Bolero"
				],
			filter_container_id: "genre-filter",
			filter_default_label: "Filter By Genre",
			filter_reset_button_text: "Reset"
	}, {	column_number: 8,
			data: [
				"Australia",
				"Brazil",
				"Canada",
				"France",
				"Germany",
				"Ireland",
				"Italy",
				"Mexico",
				"New Zealand",
				"Norway",
				"Philippines",
				"Scotland",
				"Spain",
				"Sweden",
				"UK",
				"USA"
				],
			filter_container_id: "country-filter",
			filter_default_label: "Filter By Country",
			filter_reset_button_text: "Reset"	
	}]);
});